### ISSUE TITLE
Wrong encoding for hash strings when reporting to gaze network

### ISSUE THREAD

**Issue by bombnp** [gaze-network/atomicals-electrumx#9]
Hi @gazenw!

I was running the node and I noticed that reported block hashes were ending with zeroes (e.g. `c46347d4ccea0d4ceefe3a84217db217224c11c9854a01000000000000000000`) instead of beginning with zeroes (e.g. [000000000000000000014a85c9114c2217b27d21843afeee4c0deaccd44763c4](https://mempool.space/block/000000000000000000014a85c9114c2217b27d21843afeee4c0deaccd44763c4)).

This is likely a bug.

**Comment by gazenw** [comment]
Thanks !!
